version: '3.4'

services:
  defaultbackend:
    image: defautlbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      "DEFAULT_PAGE": "OriginalURI" 